### ISSUE TITLE
ValueError: The passed save_path is not a valid checkpoint: ../model/ens3_adv_inception_v3_rename.ckpt

### ISSUE THREAD

**Issue by zhoufengfan** [huitailangyz/MGAA#1]
Could you add the download and pre-preparation script of the pre-trained models in the repo?

Thanks a lot.

**Comment by huitailangyz** [comment]
We have updated the README.md, and you can use the misc.py to pre-process the checkpoint files.

**Comment by zhoufengfan** [comment]
I have run `misc.py`. However, there still occurs this error.

**Comment by huitailangyz** [comment]
We have checked that the code is valid. You can check the following things.
1. You have downloaded the correct and integrated checkpoint models from the link.
2. You have unzipped the models from the *.tar.gz and placed the unzipped files in the right path.
3. You have processed all models mentioned in the README.md with misc.py, but not only the model written in misc.py

**Comment by zhoufengfan** [comment]
Thanks for your response.

Should I rename the file I have downloaded from Google manually(for example, change all `ens3_adv_inception_v3` to `ens3_adv_inception_v3_rename` after processing them with ` misc.py`)?

**Comment by huitailangyz** [comment]
Yes, you are right.

**Comment by zhoufengfan** [comment]
If I want to process `adv_inception_v3`, should I change `misc.py` like this:
``` python
import tensorflow as tf
import tensorflow.contrib.slim as slim

def name_in_checkpoint(name):
  return name.replace('AdvInceptionV3', 'AdvInceptionV3.4')
  # return 'nasnet_mobile/' + name

def rename_var(ckpt_path, new_ckpt_path):
    with tf.Session() as sess:
        for var_name, _ in tf.contrib.framework.list_variables(ckpt_path):
            var = tf.contrib.framework.load_variable(ckpt_path, var_name)
            new_var_name = name_in_checkpoint(var_name)
            var = tf.Variable(var, name=new_var_name)

        saver = tf.train.Saver()
        sess.run(tf.global_variables_initializer())
        saver.save(sess, new_ckpt_path)

old_path = "../model/adv_inception_v3.ckpt"
new_path = "../model/adv_inception_v3_test.ckpt"
rename_var(old_path, new_path)
```

**Comment by huitailangyz** [comment]
Sorry for missing your reply.
As I mentioned in README.md, "For adv_inception_v3_rename.ckpt, we replace variable scope of InceptionV3 with AdvInceptionV3 at the beginning of the variable names."
So for `adv_inception_v3`, you should modify as follows:
```python
import tensorflow as tf
import tensorflow.contrib.slim as slim

def name_in_checkpoint(name):
  return name.replace('InceptionV3', 'AdvInceptionV3')
  # return 'nasnet_mobile/' + name

def rename_var(ckpt_path, new_ckpt_path):
    with tf.Session() as sess:
        for var_name, _ in tf.contrib.framework.list_variables(ckpt_path):
            var = tf.contrib.framework.load_variable(ckpt_path, var_name)
            new_var_name = name_in_checkpoint(var_name)
            var = tf.Variable(var, name=new_var_name)

        saver = tf.train.Saver()
        sess.run(tf.global_variables_initializer())
        saver.save(sess, new_ckpt_path)

old_path = "../model/adv_inception_v3.ckpt"
new_path = "../model/adv_inception_v3_rename.ckpt"
rename_var(old_path, new_path)

```

**Comment by SuperCarryFu** [comment]
Excuse me, my English is not standard.
Do you have all the models that have been processed? Can you upload them to me?
